### ISSUE TITLE
您好，您翻译的好像并不是Java虚拟机规范，而是Java语言规范。

### ISSUE THREAD

**Issue by willenigma** [waylau/java-virtual-machine-specification#11]
[https://docs.oracle.com/javase/specs/jls/se11/html/index.html](https://docs.oracle.com/javase/specs/jls/se11/html/index.html)，这个是Java语言规范，也就是您翻译的。

[https://docs.oracle.com/javase/specs/jvms/se11/html/index.html](https://docs.oracle.com/javase/specs/jvms/se11/html/index.html)，这个才是Java虚拟机规范。

祝好！

**Comment by zjjxcxj** [comment]
you are right

**Comment by tianyw0** [comment]
建议作者改改名字，搜索引擎会把很多人导到这里..
@waylau

**Comment by waylau** [comment]
@TianYongwei   好的。后期有时间我调整下内容。

本意，确实是想翻译 Java虚拟机规范的内容。只是把另外一本的内容，搞混了。
